In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]], dtype=float)

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
 np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [11]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
 np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [13]:
np.random.random((2, 2))

array([[0.783642  , 0.14469065],
       [0.74283377, 0.78489383]])

In [14]:
print("a: shape =", a.shape, ", ndim =", a.ndim, ", size =", a.size)
print("b: shape =", b.shape, ", ndim =", b.ndim, ", size =", b.size)
print("c: shape =", c.shape, ", ndim =", c.ndim, ", size =", c.size)


a: shape = (3,) , ndim = 1 , size = 3
b: shape = (2, 3) , ndim = 2 , size = 6
c: shape = (2, 2, 3) , ndim = 3 , size = 12


In [15]:
import numpy as np

b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

print("dtype:", b.dtype)
print("dtype name:", b.dtype.name)

b_int = b.astype(int)
print("\nConverted to int:")
print(b_int)


dtype: float64
dtype name: float64

Converted to int:
[[1 2 3]
 [4 5 6]]


In [16]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

add_result = a + b
print("a + b =\n", add_result)

sub_result = a - b
print("\na - b =\n", sub_result)


a + b =
 [[2.5 4.  6. ]
 [5.  7.  9. ]]

a - b =
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [17]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
mul_result = b * b
div_result = b / b

print("b * b =\n", mul_result)
print("\nb / b =\n", div_result)


b * b =
 [[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]

b / b =
 [[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
import numpy as np

sqrt_b = np.sqrt(b)
print(sqrt_b)
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)


[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [19]:
import numpy as np

b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

print("Sum:", np.sum(b))
print("Min:", np.min(b))
print("Max:", np.max(b))
print("Cumulative Sum:\n", np.cumsum(b))
print("Mean:", np.mean(b))
print("Median:", np.median(b))
print("Standard Deviation:", np.std(b))


Sum: 21.5
Min: 1.5
Max: 6.0
Cumulative Sum:
 [ 1.5  3.5  6.5 10.5 15.5 21.5]
Mean: 3.5833333333333335
Median: 3.5
Standard Deviation: 1.5920810978785667
